# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setLivreApp', '0002_auto_20170209_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setLivreApp.Integrante'),
        ),
    ]
